import { StyleSheet } from "react-native";
import { ThemeType } from "../../../../styles/theme";

export const createStyles = (theme: ThemeType) => StyleSheet.create({
    container: {
        flex: 1,
        padding: 10,
    },
    heading: {
        fontSize: 20,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginBottom: 8,
        textAlign: 'left',
        textTransform: 'uppercase',
    },
    medidasContainer: {
        padding: 20,
        backgroundColor: theme.colors.surface,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 20,
        marginTop: 10,
    },
    medidasList: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 8, 
        marginBottom: 8,
    },
    medidaCard: {
        flex: 1,
        alignItems: 'center',
        backgroundColor: theme.colors.background,
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: theme.colors.border,
    },
    medidaLabel: {
        fontSize: 12,
        color: theme.colors.textLight,
        marginTop: 8,
    },
    medidaValue: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginTop: 4,
    },
    preferenciasContainer: {
        padding: 20,
        backgroundColor: theme.colors.surface,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 20,
        marginTop: 20,
    },
    preferenciasTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: theme.colors.textLight,
        marginBottom: 10,
    },
    preferenciasList: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'flex-start',
        gap: 8,
        marginBottom: 16,
    },
    preferenciasCoisasQueAmoItem: {
        backgroundColor: '#E8F5E9',
        color: '#2E7D32',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        fontSize: 14,
        fontWeight: '500',
        borderWidth: 1,
        borderColor: '#C8E6C9',
    },
    preferenciasMelhorEvitarItem: {
        backgroundColor: '#FFEBEE',
        color: '#C62828',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        fontSize: 14,
        fontWeight: '500',
        borderWidth: 1,
        borderColor: '#FFCDD2',
    },
});