import { StyleSheet } from 'react-native';
import { theme } from '../../styles/theme';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: theme.colors.background,
    },
    content: {
        flex: 1,
        paddingHorizontal: 24,
        paddingTop: 16,
    },
    text: {
        fontSize: 18,
        color: theme.colors.text,
    },
    footer: {
        position: 'relative',
        paddingVertical: 12,
        paddingHorizontal: 24,
        backgroundColor: theme.colors.background,
    },
    backdrop: {
        ...StyleSheet.absoluteFillObject,
        zIndex: 9998,
        backgroundColor: 'transparent',
    },
    messageToast: {
        position: 'absolute',
        bottom: 80,
        left: 24,
        right: 24,
        backgroundColor: 'transparent',
        padding: 12,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 9999,
    },
    successText: {
        color: theme.colors.success,
        fontSize: 14,
        textAlign: 'center',
        fontWeight: '600',
    },
    errorText: {
        color: theme.colors.danger,
        fontSize: 14,
        textAlign: 'center',
        fontWeight: '600',
    },
    errorBanner: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FDE8E8',
        borderColor: '#F8B4B4',
        borderWidth: 1,
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
    },
    errorBannerText: {
        flex: 1,
        color: theme.colors.danger,
        fontSize: 14,
        fontWeight: '500',
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        color: theme.colors.text,
        marginTop: 12,
        marginBottom: 8,
    },
    firstSectionTitle: {
        marginTop: 4,
    },
    bioCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.metrics.borderRadius,
        padding: 16,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: theme.colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    bioTextInput: {
        fontSize: 15,
        color: theme.colors.text,
        textAlignVertical: 'top',
        minHeight: 80,
        padding: 0,
    },
    sizesRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 10,
        marginHorizontal: -4,
    },
    card: {
        flex: 1,
        backgroundColor: theme.colors.surface,
        borderRadius: theme.metrics.borderRadius,
        padding: 8,
        marginHorizontal: 4,
        borderWidth: 1,
        borderColor: theme.colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
        alignItems: 'center',
    },
    cardIconContainer: {
        height: 38,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 4,
        marginTop: 8,
    },
    cardEmoji: {
        fontSize: 32,
    },
    cardTitle: {
        fontSize: 11,
        fontWeight: 'bold',
        color: theme.colors.text,
        textAlign: 'center',
        marginBottom: 8,
        height: 28,
    },
    dropdownContainer: {
        width: '100%',
        position: 'relative',
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderRadius: 6,
        backgroundColor: theme.colors.background,
        overflow: 'hidden',
        minHeight: 48,
    },
    dropdownVisual: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 6,
        paddingVertical: 4,
        minHeight: 48,
    },
    dropdownTextWrapper: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
    },
    dropdownValueText: {
        fontSize: 13,
        fontWeight: 'bold',
        color: theme.colors.text,
        textAlign: 'center',
    },
    dropdownPlaceholderText: {
        fontSize: 9,
        color: theme.colors.textLight,
        textAlign: 'center',
        lineHeight: 12,
    },
    picker: {
        position: 'absolute',
        left: 0,
        top: 0,
        right: 0,
        bottom: 0,
        opacity: 0.01,
        width: '100%',
        height: '100%',
    },
    chevron: {
        marginLeft: 2,
    },
    interestsCard: {
        backgroundColor: theme.colors.surface,
        borderRadius: theme.metrics.borderRadius,
        padding: 16,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: theme.colors.border,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    interestsContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 12,
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#EFEFEF',
        borderRadius: 16,
        paddingHorizontal: 10,
        paddingVertical: 5,
        margin: 4,
    },
    chipText: {
        fontSize: 13,
        color: theme.colors.text,
        marginRight: 4,
    },
    chipRemoveButton: {
        padding: 2,
    },
    addInterestRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomWidth: 1,
        borderBottomColor: theme.colors.border,
        paddingBottom: 4,
    },
    addChipButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: theme.colors.surface,
        borderWidth: 1,
        borderColor: theme.colors.border,
        borderStyle: 'dashed',
        borderRadius: 16,
        paddingHorizontal: 10,
        paddingVertical: 5,
        margin: 4,
    },
    addChipText: {
        fontSize: 13,
        color: theme.colors.text,
        marginRight: 4,
    },
    interesseTextInput: {
        flex: 1,
        fontSize: 14,
        color: theme.colors.text,
        paddingVertical: 6,
        paddingHorizontal: 4,
    },
});
